### ISSUE TITLE
Broken theme_map link

### ISSUE THREAD

**Issue by joshualeond** [ricardo-bion/medium_visualization#1]
Hi Ricardo,

Thanks for releasing this work. I was just trying to replicate the analysis and I see that the dropbox link has a 404 error now:

> https://dl.dropboxusercontent.com/u/2364714/theme_map.R

Is it possible for you to add this R script file to the repo or update the link?

Thanks again.

**Comment by ricardo-bion** [comment]
https://github.com/ricardo-bion/medium_visualization/blob/master/theme_map.R

**Comment by ricardo-bion** [comment]
@joshualeond Thanks for pointing it out!
